# QUESTION1

In [1]:
import numpy as np
tableau = np.array([[1, 2, 3], [4, 5, 6]])
liste = tableau.tolist()
print(liste)

[[1, 2, 3], [4, 5, 6]]


# QUESTION2

In [2]:
import numpy as np

# Créer un tableau de test
tableau = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculer la somme des éléments diagonaux en utilisant la fonction trace()
somme = np.trace(tableau)

# Afficher le résultat
print("La somme des éléments diagonaux du tableau est :", somme)

La somme des éléments diagonaux du tableau est : 15


# QUESTION3

In [3]:
import numpy as np

# Créer un tableau de test
tableau = np.array([[1, 2], [3, 5]])

# Définir la valeur de X
X = 2

# Obtenir toutes les valeurs supérieures à X
valeurs_sup = tableau[tableau > X]

# Afficher les valeurs supérieures à X
print("Les valeurs supérieures à", X, "sont :", valeurs_sup)

Les valeurs supérieures à 2 sont : [3 5]


# QUESTION4

In [4]:
import numpy as np

# Créer deux tableaux de test
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Initialiser le tableau C
C = np.zeros_like(A)

# Appliquer l'addition manuellement
for i in range(len(A)):
    for j in range(len(A[0])):
        C[i][j] = A[i][j] + B[i][j]

# Afficher le résultat
print("Le nouveau tableau C est :", C)

Le nouveau tableau C est : [[ 6  8]
 [10 12]]


# QUESTION6

In [5]:
import numpy as np

# Créer une matrice de test
matrice = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculer la moyenne de chaque ligne
moyennes = np.mean(matrice, axis=1)

# Soustraire la moyenne de chaque ligne
matrice_soustraite = matrice - moyennes.reshape(-1, 1)

# Afficher les résultats
print("La matrice originale :\n", matrice)
print("La moyenne de chaque ligne :", moyennes)
print("La matrice soustraite de la moyenne de chaque ligne :\n", matrice_soustraite)


La matrice originale :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
La moyenne de chaque ligne : [2. 5. 8.]
La matrice soustraite de la moyenne de chaque ligne :
 [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
